# This is a basic workflow to help you get started with Actions

name: Kernel Build (LLVM)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential bc flex bison libssl-dev ccache \
            clang lld llvm python3-pip git libncurses-dev gawk

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/bhazheng/kernel_lge_sm8250.git kernel
          cd kernel

      - name: Remove KernelSU from Kconfig
        run: |
          cd kernel
          sed -i '/drivers\/kernelsu\/Kconfig/d' drivers/Kconfig

      - name: Disable KernelSU in Defconfig
        run: |
          cd kernel
          sed -i '/CONFIG_KSU/d' arch/arm64/configs/vendor/timelm-perf_defconfig

      - name: Compile Kernel (Clang + GCC)
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH="/usr/bin:$PATH"

          # Pakai Clang untuk compile utama
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-

          # Tambah flag debugging
          export MAKEFLAGS="V=1"

          # Gunakan defconfig yang ada di vendor
          make mrproper
          make clean
          make vendor/timelm-perf_defconfig
          make LLVM=1 LLVM_IAS=1 -j$(nproc)
